name: Dotnet Format

env:
  DOTNET_VERSION: "10.0.x"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - BinDays.Api/**
      - BinDays.Api.Collectors/**
  pull_request:
    paths:
      - BinDays.Api/**
      - BinDays.Api.Collectors/**

jobs:
  dotnet_format:
    name: Dotnet Format
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Format code
        run: dotnet format --no-restore --severity info

      - name: Commit changes
        run: |
          git config --global user.email "moley-bot@users.noreply.github.com"
          git config --global user.name "Moley-Bot"
          git add .
          git diff-index --quiet HEAD -- || (
            git commit -am "Auto-format code with dotnet format

            Formatted by Moley-Bot"
            git push
          )
